name: TogglePVP
version: '1.0-SNAPSHOT'
main: org.eggstudios.togglePVP.TogglePVP
api-version: '1.21'
commands:
  pvp:
    description: Allows you to show other players if you want to PVP or not.
    usage: /pvp [on|off]
    permission: togglepvp.toggle
    permission-message: §cOnly players can use this command!
