name: TogglePVP
version: '1.0-SNAPSHOT'
main: org.eggstudios.togglePVP.TogglePVP
api-version: '1.21'
commands:
  pvp:
    description: To Toggle PVP on, loot or off.
    usage: /togglepvp [pvp|loot|off]
    permission: togglepvp.toggle
    permission-message: §cOnly players can use this command!

